---
kind: pipeline
type: docker
name: default

steps:
- name: install, build doc run scripts
  image: python:3.9
  commands:
  - git fetch --tags
  - bash install_deps.sh
  - python setup.py install
  - python tests.py

- name: weekly install, build doc run scripts
  image: python:3.9
  commands:
  - git fetch --tags
  - python setup.py install
  - python tests.py
  when:
    event:
      - cron
    cron:
      - "0 * * * *"  # Run every hour
#      - "0 7 * * 1"  # Run every Monday at 7 AM


- name: notify by email
  # when:
    # status:
    # - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
      from_secret: email_password
    from: technical@dessia.tech
    recipients: [ younes.belabid@dessia.io, ringhausen@dessia.io ]
